[package]
name = "power_core"
version = "0.1.0"
authors = ["Patrik Dvořáček <patrik@dvoracek.dev>"]
edition = "2018"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
bootloader = "0.9.14"
volatile = "0.2.6"
spin = "0.7.1"

[dependencies.lazy_static]
varsion = "1.4.0"
features = ["spin_no_std"]