blank_lines_lower_bound = 0
blank_lines_upper_bound = 2
combine_control_expr = false
enum_discrim_align_threshold = 20
force_multiline_blocks = true
format_code_in_doc_comments = true
format_strings = true
hard_tabs = true
imports_layout = "HorizontalVertical"
indent_style = "Visual"
imports_granularity = "Crate"
normalize_doc_attributes = true
reorder_impl_items = true
group_imports = "StdExternalCrate"
trailing_comma = "Always"
wrap_comments = true